config/urls.py
from debug_toolbar.toolbar import debug_toolbar_urls

from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("users/", include("users.urls", namespace="users")),
    path("", include("shortener.urls", namespace="shortener")),
] + debug_toolbar_urls()

shortener/urls.py
from django.urls import path

from shortener import views

app_name = "shortener"
urlpatterns = [
    path("", views.HomePage.as_view(), name="home"),
    path(
        "u/<str:code>/",
        views.RedirectByShortUrl.as_view(),
        name="redirect-by-short-url",
    ),
    path("short-url/create/", views.CreateShortURL.as_view(), name="create-short-url"),
    path(
        "short-url/create/done/<str:code>/",
        views.CreateShortURLDone.as_view(),
        name="create-short-url-done",
    ),
    path("short-url/list/", views.ListShortURL.as_view(), name="list-short-url"),
    path(
        "short-url/<int:pk>/", views.DetailShortURL.as_view(), name="detail-short-url"
    ),
    path(
        "short-url/<int:pk>/change/",
        views.ChangeShortURL.as_view(),
        name="change-short-url",
    ),
    path(
        "short_url/<int:pk>/delete/",
        views.DeleteShortURL.as_view(),
        name="delete-short-url",
    ),
]

users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from users import views

app_name = "users"
urlpatterns = [
    path("login/", views.LoginUser.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("register/", views.RegisterUser.as_view(), name="register"),
]

shortener/models.py
from typing import Self

from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse

from shortener.validators import code_contains_only_allowed_chars


class ShortURL(models.Model):
    title = models.CharField(verbose_name="Название", blank=True)
    url = models.URLField(verbose_name="URL")
    code = models.CharField(
        verbose_name="URL код",
        unique=True,
        max_length=50,
        blank=True,
        validators=[code_contains_only_allowed_chars],
        error_messages={"unique": "Указанный URL код уже существует."},
        db_index=True,
    )
    owner = models.ForeignKey(
        get_user_model(),
        on_delete=models.CASCADE,
        related_name="urls",
        verbose_name="Владелец",
    )
    created_at = models.DateTimeField(verbose_name="Дата создания", auto_now_add=True)

    class Meta:
        ordering = ["-created_at"]
        verbose_name = "Короткая ссылка"
        verbose_name_plural = "Короткие ссылки"
        constraints = [
            models.UniqueConstraint(
                fields=["url", "owner"],
                name="unique_url_owner",
                violation_error_message=(
                    "У пользователя уже есть короткий URL для указанного URL."
                ),
            )
        ]

    def __str__(self) -> str:
        return f"Url: {self.url} Code: {self.code}"

    def __repr__(self) -> str:
        return "{cls_name}(url={url}, code={code})".format(
            cls_name=self.__class__.__name__,
            url=self.url,
            code=self.code,
        )

    def get_absolute_url(self) -> str:
        return reverse("shortener:detail-short-url", kwargs={"pk": self.pk})

    @classmethod
    def get_object_or_none(cls, **filters) -> Self | None:  # noqa:ANN003
        """Возвращает ShortURL по фильтрам или None, если его не существует"""
        try:
            obj = cls.objects.get(**filters)
        except cls.DoesNotExist:
            return None
        return obj

shortener/forms.py
from typing import Any

from django import forms

from shortener.exceptions import RetryLimitReachedError
from shortener.models import ShortURL
from shortener.services import generate_unique_code, get_url_title


class CreateShortUrlForm(forms.ModelForm):
    def clean(self) -> dict[str, Any]:
        if not self.cleaned_data["code"]:
            try:
                self.cleaned_data["code"] = generate_unique_code()
            except RetryLimitReachedError:
                self.add_error(
                    field="code",
                    error=forms.ValidationError(
                        "Не удалось создать короткий URL. Попробуйте ещё раз."
                    ),
                )
        if not self.cleaned_data["title"]:
            self.cleaned_data["title"] = get_url_title(self.cleaned_data["url"])
        return super().clean()

    class Meta:
        model = ShortURL
        fields = ["url", "title", "code"]
        labels = {
            "title": "Название (Не обязательно)",
            "code": "URL код (Не обязательно)",
        }


class UpdateShortURL(CreateShortUrlForm):
    class Meta(CreateShortUrlForm.Meta):
        model = ShortURL
        labels = {
            "title": "Название",
            "code": "URL код",
        }

shortener/views.py
from typing import Any

from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import Paginator
from django.db.models.query import QuerySet
from django.http import Http404
from django.http.request import HttpRequest
from django.http.response import HttpResponse
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views.generic import (
    CreateView,
    DeleteView,
    DetailView,
    ListView,
    RedirectView,
    TemplateView,
    UpdateView,
    View,
)

from shortener.forms import CreateShortUrlForm, UpdateShortURL
from shortener.models import ShortURL


class HomePage(TemplateView):
    template_name = "shortener/home.html"


class CreateShortURL(LoginRequiredMixin, CreateView):
    template_name = "shortener/create_short_url.html"
    form_class = CreateShortUrlForm

    def form_valid(self, form: CreateShortUrlForm) -> HttpResponse:
        filters = {
            "url": form.cleaned_data["url"],
            "owner": self.request.user,
        }
        if ShortURL.get_object_or_none(**filters) is not None:
            form.add_error(
                field="url", error="У вас уже есть короткий URL для указанного URL."
            )
            return super().form_invalid(form)
        short_url = form.save(commit=False)
        short_url.owner = self.request.user
        self.kwargs["code"] = short_url.code
        return super().form_valid(form)

    def get_success_url(self) -> str:
        return reverse(
            "shortener:create-short-url-done", kwargs={"code": self.kwargs.get("code")}
        )


class CreateShortURLDone(LoginRequiredMixin, View):
    def get(self, request: HttpRequest, **kwargs) -> HttpResponse:  # noqa:ANN003
        short_url = get_object_or_404(ShortURL, code=kwargs.get("code"))
        if not short_url.owner == request.user:
            raise Http404
        context = {
            "short_url": short_url,
        }
        return render(request, "shortener/create_short_url_done.html", context)


class RedirectByShortUrl(RedirectView):
    permanent = True

    def get_redirect_url(self, **kwargs) -> str:  # noqa:ANN003
        short_url = get_object_or_404(ShortURL, code=kwargs.get("code"))
        return short_url.url


class ListShortURL(LoginRequiredMixin, ListView):
    template_name = "shortener/list_short_url.html"
    paginator_class = Paginator
    paginate_by = 4

    def get_queryset(self) -> QuerySet[Any]:
        return ShortURL.objects.filter(owner=self.request.user)


class DetailShortURL(LoginRequiredMixin, DetailView):
    template_name = "shortener/detail_short_url.html"

    def get_queryset(self) -> QuerySet[ShortURL]:
        return ShortURL.objects.filter(owner=self.request.user)


class ChangeShortURL(LoginRequiredMixin, UpdateView):
    template_name = "shortener/change_short_url.html"
    form_class = UpdateShortURL

    def get_queryset(self) -> QuerySet[ShortURL]:
        return ShortURL.objects.filter(owner=self.request.user)


class DeleteShortURL(LoginRequiredMixin, DeleteView):
    template_name = "shortener/delete_short_url.html"

    def get_queryset(self) -> QuerySet[Any]:
        return ShortURL.objects.filter(owner=self.request.user)

    def get_success_url(self) -> str:
        return reverse("shortener:list-short-url")

users/views.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.views import LoginView
from django.urls import reverse_lazy
from django.views.generic import CreateView


class LoginUser(LoginView):
    template_name = "users/login.html"
    redirect_authenticated_user = True


class RegisterUser(CreateView):
    form_class = UserCreationForm
    template_name = "users/register.html"
    success_url = reverse_lazy("users:login")

shortener/templates/shortener/change_short_url.html
{% extends "base.html" %}

{% load static %}

{% block title %}Изменение ссылки "{{object.title}}"{% endblock title %}
{% block extra_head %}
<link rel="stylesheet" href="{% static "shortener/css/style.css" %}">
{% endblock extra_head %}

{% block content %}
<div class="login-container">
    <form class="login-form" action="{% url "shortener:change-short-url" object.pk %}" method="POST">
        <h2>Изменить ссылку</h2>
        {% if form.non_field_errors %}
        {{form.non_field_errors}}
        <br>
        {% endif %}
        {% csrf_token %}
        {% for field in form %}
        <div class="input-group">
            {{field.label_tag}}
            {% if field.errors %}
            {{field.errors}}
            <br>
            {% endif %}
            {{field}}
        </div>
        {% endfor %}
        <div id="block-field-preview" class="input-group">
            <label for="preview-field">Как выглядит ваша ссылка:</label>
            <input type="text" id="preview-field" name="preview-field" readonly>
        </div>
        <button type="submit" class="btn-login">Созранить</button>
    </form>
    <script src="{% static 'shortener/js/auto_field_filling.js' %}"></script>
</div>
{% endblock content %}

shortener/templates/shortener/create_short_url.html
{% extends "base.html" %}

{% load static %}

{% block title %}Сокращатель ссылок{% endblock title %}

{% block extra_head %}
<link rel="stylesheet" href="{% static "shortener/css/style.css" %}">
{% endblock extra_head %}

{% block content %}
<div class="login-container">
    <form class="login-form" action="{% url "shortener:create-short-url" %}" method="POST">
        <h2>Сократить ссылку</h2>
        {% if form.non_field_errors %}
        {{form.non_field_errors}}
        <br>
        {% endif %}
        {% csrf_token %}
        {% for field in form %}
        <div class="input-group">
            {{field.label_tag}}
            {% if field.errors %}
            {{field.errors}}
            <br>
            {% endif %}
            {{field}}
        </div>
        {% endfor %}
        <div id="block-field-preview" class="input-group">
            <label for="preview-field">Как выглядит ваша ссылка:</label>
            <input type="text" id="preview-field" name="preview-field" readonly>
        </div>
        <button type="submit" class="btn-login">Создать короткую ссылку</button>
    </form>
    <script src="{% static 'shortener/js/auto_field_filling.js' %}"></script>
</div>
{% endblock content %}

shortener/templates/shortener/create_short_url_done.html
{% extends "base.html" %}

{% load static %}

{% block title %}Короткая ссылка успешно создана{% endblock title %}

{% block extra_head %}
<link rel="stylesheet" href="{% static "shortener/css/style.css" %}">
{% endblock extra_head %}

{% block content %}
<div class="success-card">
    <div class="success-title">Ссылка успешно создана!</div>
    <div class="success-message">Cсылка была успешно добавлена в ваш профиль.</div>
    <div class="success-message">
        <p>Название:</p>
        <b>{{short_url.title}}</b> 
    </div>
    <div class="success-message">
        <p>URL код:</p>
        <b>{{short_url.code}}</b> 
    </div>
    <div class="success-message">
        <p>Короткая ссылка:</p>
        {% with href_url='http://127.0.0.1:8000/u/'|add:short_url.code|add:'/' %}
        <a class="success-link" href="{{href_url}}">{{href_url}}</a>
        {% endwith %}
    </div>
    <div class="success-message">
        <p>Целевая ссылка:</p>
        <a class="success-link" href="{{short_url.url}}">{{short_url.url}}</a>
    </div>
    <div class="success-btn-container">
        <a class="success-btn" href="{% url "shortener:create-short-url" %}">Создать новую ссылку</a>
        <a class="success-btn" href="{% url "shortener:list-short-url" %}">Список ссылок</a>
    </div>
</div>
{% endblock content %}

shortener/templates/shortener/delete_short_url.html
{% extends "base.html" %}

{% load static %}

{% block title %}Удаление короткой ссылки "{{object.title}}"{% endblock title %}

{% block extra_head %}
<link rel="stylesheet" href="{% static "shortener/css/style.css" %}">
{% endblock extra_head %}

{% block content %}
<div class="short-url-detail-container">
    <h4 class="short-url-detail-h4">Подтверждение удаления</h4>
    <p class="short-url-delete-warning">Вы действительно хотите удалить короткую ссылку?</p>
    <div class="short-url-detail-fields-container">
        <div class="short-url-detail-field-group">
            <label>Название:</label>
            <p>{{object.title}}</p>
        </div>
        <div class="short-url-detail-field-group">
            <label>Целевая ссылка:</label>
            <p><a href="{{object.url}}">{{object.url}}</a></p>
        </div>
        <div class="short-url-detail-field-group">
            <label>Короткая ссылка:</label>
            <p><a href="http://127.0.0.1:8000/u/{{object.code}}/">http://127.0.0.1:8000/u/{{object.code}}/</a></p>
        </div>
    </div>
    <div class="short-url-detail-actions">
        <a style="color: black" href="{{ object.get_absolute_url }}" class="short-url-action-button">↩</a>
        <form method="post" action="{% url "shortener:delete-short-url" object.pk %}">
            {% csrf_token %}
            <button type="submit" style="color: black" class="short-url-action-button">Удалить</a>
        </form>
    </div>
</div>
{% endblock content %}

shortener/templates/shortener/detail_short_url.html
{% extends "base.html" %}

{% load static %}

{% block title %}Детали короткой ссылки "{{object.title}}"{% endblock title %}

{% block extra_head %}
<link rel="stylesheet" href="{% static "shortener/css/style.css" %}">
{% endblock extra_head %}

{% block content %}
<div class="short-url-detail-container">
    <h4 class="short-url-detail-h4">Детали ссылки</h4>
    <div class="short-url-detail-fields-container">
        <div class="short-url-detail-field-group">
            <label>Название:</label>
            <p>{{object.title}}</p>
        </div>
        <div class="short-url-detail-field-group">
            <label>Целевая ссылка:</label>
            <p><a href="{{object.url}}">{{object.url}}</a></p>
        </div>
        <div class="short-url-detail-field-group">
            <label>Короткая ссылка:</label>
            <p><a href="http://127.0.0.1:8000/u/{{object.code}}/">http://127.0.0.1:8000/u/{{object.code}}/</a></p>
        </div>
    </div>
    <div class="short-url-detail-actions">
        <a style="color: black" href="{% url "shortener:list-short-url" %}" class="short-url-action-button">↩</a>
        <a href="{% url "shortener:change-short-url" object.pk %}" class="short-url-action-button">✏️</a>
        <a href="#" class="short-url-action-button">🗑️</a>
    </div>
</div>
{% endblock content %}

shortener/templates/shortener/home.html
{% extends "base.html" %}

{% load static %}

{% block extra_head %}
<link rel="stylesheet" href="{% static "shortener/css/style.css" %}">
{% endblock extra_head %}

{% block title %}Главная{% endblock title %}

{% block content %}
<div class="info-section">
    <h1>Удобный сервис для сокращения ссылок</h1>
    <p class="lead">
        Превращайте длинные URL в короткие и удобные ссылки за секунды. 
    </p>
    <div class="features-grid">
        <div class="feature-card">
            <h3>Просто</h3>
            <p>Вставьте ссылку — получите короткий URL. Никаких сложных настроек.</p>
        </div>
        <div class="feature-card">
            <h3>Быстро</h3>
            <p>Сокращение занимает меньше секунды.</p>
        </div>
        <div class="feature-card">
            <h3>Свои названия</h3>
            <p>Возможность создавать ссылки со своим названием.</p>
        </div>
        <div class="feature-card">
            <h3>Профиль</h3>
            <p>Профиль со всеми вашими созданными ссылками.</p>
        </div>
        <div class="feature-card">
            <h3>Редактирование</h3>
            <p>Возможность редактировать свои ссылки.</p>
        </div>
        <div class="feature-card">
            <h3>Время жизни</h3>
            <p>Создание ссылок с временем жизни.</p>
        </div>
    </div>
    <div class="cta-container">
        <a href="{% url "shortener:create-short-url" %}" class="btn-cta">Перейти к сокращателю</a>
    </div>
</div>
{% endblock content %}

shortener/templates/shortener/list_short_url.html
{% extends "base.html" %}

{% load static %}

{% block extra_head %}
<link rel="stylesheet" href="{% static "shortener/css/style.css" %}">
{% endblock extra_head %}

{% block title %}Список коротких URL{% endblock title %}


{% block content %}
<div class="list-url-container">
    {% if not object_list %}
    <div class="empty-short-urls">
        <div>У вас нет коротких ссылок.</div>
        <div>Создать короткие ссылки можно <a href="{% url "shortener:create-short-url" %}">здесь</a>.</div>
    </div>
    {% else %}
    <h2 class="short-urls-title">Список коротких URL</h2>
    <div class="short-urls-container">
        {% for url in object_list %}
        <div class="short-url-card-container">
            <div class="short-url-card">
                <div class="short-url-card-main-info">
                    <h3 class="short-url-card-short-url-name">
                        <a class="short-url-card-detail-url" href="{{ url.get_absolute_url }}">{{url.title}}</a>
                    </h3>
                    <div class="short-url-card-short-url">
                        {% with short_url='http://127.0.0.1:8000/u/'|add:url.code|add:'/' %}
                        <a class="url" href="{{short_url}}">{{short_url}}</a>
                        {% endwith %}
                    </div>
                </div>
                <div class="short-url-card-actions">
                    <a href="{% url "shortener:change-short-url" url.pk %}" class="short-url-action-button">✏️</a>
                    <a href="{% url "shortener:delete-short-url" url.pk %}" class="short-url-action-button">🗑️</a>
                </div>
                <div class="short-url-card-destination-url">
                    <p class="short-url-curved-arrow">⤷</p><a class="url" href="{{url.url}}">{{url.url}}</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    {% if paginator.num_pages > 1 %}
    <div class="pagination-container">
        <ul class="paginator-block">
            <div class="paginator-left-side">
                {% if page_obj.number != 1 %}
                <li class="page-item"><a href="?page=1" class="page-link">1</a></li>
                {% endif %}
                {% if page_obj.number > 3 %}
                <li class="page-item"><p class="page-link disabled">...</p></li>
                {% endif %}
                {% if page_obj.number > 2 %}
                <li class="page-item">
                    <a href="?page={{page_obj.previous_page_number}}" class="page-link">
                    {{page_obj.previous_page_number}}
                    </a>
                </li>
                {% endif %}
            </div>
            <div class="paginator-middle-side">
                <li class="page-item"><p class="page-link active">{{page_obj.number}}</p></li>
            </div>
            <div class="paginator-right-side">
                {% if page_obj.number < paginator.num_pages|add:-1 %}
                <li class="page-item">
                    <a href="?page={{page_obj.number|add:1}}" class="page-link">
                    {{page_obj.number|add:1}}
                    </a>
                </li>
                {% endif %}
                {% if page_obj.number < paginator.num_pages|add:-2 %}
                <li class="page-item">
                    <p class="page-link disabled">...</p>
                </li>
                {% endif %}

                {% if page_obj.number != paginator.num_pages %}
                <li class="page-item">
                    <a href="?page={{paginator.num_pages}}" class="page-link">{{paginator.num_pages}}</a>
                </li>
                {% endif %}
            </div>
        </ul>
    </div>
    {% endif %}
    {% endif %}
</div>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static "css/style.css" %}">
    {% block extra_head %}{% endblock extra_head %}
    <title>{% block title %}{% endblock title %}</title>
</head>
<body>
    <header class="header">
        <nav class="nav">
            <ul class="nav-list">
                <li class="nav-item"><a href="{% url "shortener:home" %}" class="nav-link">Главная</a></li>
                <li class="nav-item"><a href="{% url "shortener:create-short-url" %}" class="nav-link">Сокращатель</a></li>
                <li class="nav-item"><a href="{% url "shortener:list-short-url" %}" class="nav-link">Список коротких URL</a></li>
            </ul>
            {% if user.is_authenticated %}
            <div class="nav-right">
                <form method="post" action="{% url "users:logout" %}">
                    {% csrf_token %}
                    <button type="submit" class="nav-link nav-link-logout">Выход</button>
                </form>
            </div>
            {% else %}
            <div class="nav-right">
                <a href="{% url "users:login" %}" class="nav-link">Войти</a>
            </div>
            {% endif %}
        </nav>
    </header>
    <main>
    {% block content %}{% endblock content %}
    </main>
</body>
</html>

users/templates/users/login.html
{% extends "base.html" %}

{% load static %}

{% block extra_head %}
<link rel="stylesheet" href="{% static "users/css/style.css" %}">
{% endblock extra_head %}

{% block title %}Авторизация{% endblock title %}


{% block content %}
<div class="login-container">
    <form class="login-form" action="{% url "users:login" %}" method="POST">
        <input type="hidden" name="next" value="{{ next }}">
        <h2>Авторизация</h2>
        {% if form.non_field_errors %}
        {{form.non_field_errors}}
        <br>
        {% endif %}
        {% csrf_token %}
        {% for field in form %}
        <div class="input-group">
            {{field.label_tag}}
            {% if field.errors %}
            {{field.errors}}
            <br>
            {% endif %}
            {{field}}
        </div>
        {% endfor %}
        <button type="submit" class="btn-login">Войти</button>
        <div class="links">
            <a href="#" class="link-forgot">Забыли пароль?</a>
            <a href="{% url "users:register" %}" class="link-register">Зарегистрироваться</a>
        </div>
    </form>
</div>
{% endblock content %}

users/templates/users/register.html
{% extends "base.html" %}

{% load static %}

{% block extra_head %}
<link rel="stylesheet" href="{% static "users/css/style.css" %}">
{% endblock extra_head %}

{% block title %}Регистрация{% endblock title %}


{% block content %}
<div class="login-container">
    <form class="login-form" action="{% url "users:register" %}" method="POST">
        <h2>Регистрация</h2>
        {% if form.non_field_errors %}
        {{form.non_field_errors}}
        <br>
        {% endif %}
        {% csrf_token %}
        {% for field in form %}
        <div class="input-group">
            {{field.label_tag}}
            {% if field.errors %}
            {{field.errors}}
            <br>
            {% endif %}
            {{field}}
        </div>
        {% endfor %}
        <button type="submit" class="btn-login">Продолжить</button>
    </form>
</div>
{% endblock content %}